# **Guided Lab - 343.2.2 - NumPy and Mathematical Calculation**

## **Objectives**
By the end of this lab, Learners will be able to:
- Describe the basics of NumPy.
- Manipulate data using NumPy arrays.
- Perform element-wise mathematical operations on arrays.
- Use NumPy functions for statistical and mathematical calculations.
- Slice and index NumPy arrays for data extraction.
- Apply common data science tasks using NumPy.

## **Introduction**
NumPy (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for multidimensional arrays, mathematical functions, and a wide range of operations on arrays. In this guided lab, you will dive into the world of NumPy and learn how to efficiently manipulate arrays, perform mathematical operations, and solve common data science tasks using this powerful library.


## **Prerequisite/Equipment**

- Python environment: Python related IDE(e.g., Anaconda, Jupyter Notebook).
- NumPy library installed (can be installed via pip or conda).

## **Submission**
- Submit your completed lab using the Start Assignment button on the assignment page in Canvas.
- Your submission can be include:
  - if you are using notebook then, all tasks should be written and submitted in a single notebook file, for example: (**your_name_labname.ipynb**).
  - if you are using python script file, all tasks should be written and submitted in a single python script file for example: **(your_name_labname.py)**.
- Add appropriate comments and any additional instructions if required.


## **Instructions**

**Example 1: Import NumPy**

Open a Python environment (e.g., Jupyter Notebook).
Import the NumPy library using **`import numpy as np.`**

**Example 2: Creating NumPy Arrays**


*   Create a 1D NumPy array from a Python list.
*   Create a 2D NumPy array from a nested Python list.
* Explore the attributes of NumPy arrays such as shape, size, and data type.






In [1]:
import numpy as np

# Create a 1D NumPy array from a Python list
python_list_1d = [1, 2, 3, 4, 5]
numpy_array_1d = np.array(python_list_1d)

# Create a 2D NumPy array from a nested Python list
python_list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_array_2d = np.array(python_list_2d)

# Explore the attributes of NumPy arrays
shape_1d = numpy_array_1d.shape
shape_2d = numpy_array_2d.shape

size_1d = numpy_array_1d.size
size_2d = numpy_array_2d.size

data_type_1d = numpy_array_1d.dtype
data_type_2d = numpy_array_2d.dtype

print("1D NumPy Array:")
print("Array:", numpy_array_1d)
print("Shape:", shape_1d)
print("Size:", size_1d)
print("Data Type:", data_type_1d)

print("\n2D NumPy Array:")
print("Array:")
print(numpy_array_2d)
print("Shape:", shape_2d)
print("Size:", size_2d)
print("Data Type:", data_type_2d)


1D NumPy Array:
Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64

2D NumPy Array:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Data Type: int64


**Example 3: Statistical and Mathematical Functions**
- Perform element-wise addition, subtraction, multiplication, and division on arrays.
- Apply basic mathematical functions (e.g., np.sin(), np.exp()) to arrays.


In [ ]:

# Perform element-wise operations on arrays
addition_result = numpy_array_1d + 10
subtraction_result = numpy_array_1d - 2 # I fixed this line that had an error ------------------------------------------------
multiplication_result = numpy_array_1d * 3
division_result = numpy_array_1d / 2

print("\nElement-wise Operations on 1D Array:")
print("Original Array:", numpy_array_1d)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)

# Apply basic mathematical functions to arrays
sin_result = np.sin(numpy_array_1d)
exp_result = np.exp(numpy_array_1d)

print("\nMathematical Functions Applied to 1D Array:")
print("Original Array:", numpy_array_1d)
print("sin Result:", sin_result)
print("exp Result:", exp_result)


Element-wise Operations on 1D Array:
Original Array: [1 2 3 4 5]
Addition Result: [11 12 13 14 15]
Subtraction Result: [-1  0  1  2  3]
Multiplication Result: [ 3  6  9 12 15]
Division Result: [0.5 1.  1.5 2.  2.5]

Mathematical Functions Applied to 1D Array:
Original Array: [1 2 3 4 5]
sin Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
exp Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


**Example 4: Statistical and Mathematical Functions**
- Calculate the mean, median, and standard deviation of an array.
- Find the minimum and maximum values in an array.

In [4]:
# Apply basic mathematical functions to arrays
sin_result = np.sin(numpy_array_1d)
exp_result = np.exp(numpy_array_1d)

print("\nMathematical Functions Applied to 1D Array:")
print("Original Array:", numpy_array_1d)
print("sin Result:", sin_result)
print("exp Result:", exp_result)

# Calculate statistics on the 1D array
mean_value = np.mean(numpy_array_1d)
median_value = np.median(numpy_array_1d)
std_deviation = np.std(numpy_array_1d)
min_value = np.min(numpy_array_1d)
max_value = np.max(numpy_array_1d)

print("\nStatistics on 1D Array:")
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Mathematical Functions Applied to 1D Array:
Original Array: [1 2 3 4 5]
sin Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
exp Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Statistics on 1D Array:
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Minimum Value: 1
Maximum Value: 5


**Example 5: Slicing and Indexing**
- Slice arrays to extract specific elements or sub-arrays.
- Use boolean indexing to filter elements based on conditions.
- Combine slicing and indexing techniques to manipulate arrays effectively.


In [5]:
# Slicing and Indexing
sliced_array = numpy_array_1d[1:4]  # Slice elements from index 1 to 3
index_condition = numpy_array_1d > 3  # Create a boolean index condition

print("\nSliced Array:")
print(sliced_array)

print("\nBoolean Indexing:")
print("Original Array:", numpy_array_1d)
print("Index Condition:", index_condition)
print("Filtered Elements:", numpy_array_1d[index_condition])

# Combining Slicing and Indexing
combined_result = numpy_array_1d[1:4][numpy_array_1d[1:4] > 3]

print("\nCombined Slicing and Indexing:")
print("Original Array:", numpy_array_1d)
print("Filtered Elements:", combined_result)



Sliced Array:
[2 3 4]

Boolean Indexing:
Original Array: [1 2 3 4 5]
Index Condition: [False False False  True  True]
Filtered Elements: [4 5]

Combined Slicing and Indexing:
Original Array: [1 2 3 4 5]
Filtered Elements: [4]


**Example 6:  Real-world example of using NumPy**

Let's consider a real-world example of using NumPy for data manipulation in the context of analyzing temperature data from a weather station.

You have a dataset with daily temperature records for a year, and you want to perform various operations and calculations on this data.

In the following example, we will use NumPy to:
- Calculate the mean, median, and standard deviation of the daily temperature data.

- Convert the temperatures from Celsius to Fahrenheit.
- Identify hot days with temperatures above 30°C.
- Count the number of hot days.
- Calculate cooling degree days, a measure of cooling requirements based on a specified base temperature.

These operations demonstrate how NumPy can simplify data manipulation and analysis, making it a powerful tool for working with real-world data in various scientific and engineering fields, including meteorology and climate science.


In [7]:
import numpy as np


# Suppose you have a year's worth of daily temperature data in Celsius
temperature_data = np.array([22.3, 23.1, 24.5, 25.8, 23.6, 26.7, 27.9, 29.2, 30.5, 24.7, 23.4, 22.1, 25.3, 26.4, 28.7, 29.8, 31.2, 32.4, 30.7, 29.5, 27.8, 26.6, 23.9, 22.5, 24.1, 25.7, 27.3, 29.6, 31.0, 33.1, 31.9])


# Calculate the mean, median, and standard deviation
mean_temperature = np.mean(temperature_data)
median_temperature = np.median(temperature_data)
std_deviation_temperature = np.std(temperature_data)


print("Mean Temperature:", mean_temperature)
print("Median Temperature:", median_temperature)
print("Standard Deviation:", std_deviation_temperature)


# Convert temperatures to Fahrenheit
temperature_data_fahrenheit = (temperature_data * 9/5) + 32


# Find days with temperatures above a certain threshold (e.g., 30°C)
hot_days = temperature_data[temperature_data > 30]


# Count the number of hot days
num_hot_days = len(hot_days)


print("Number of Hot Days:", num_hot_days)


# Calculate the total cooling degree days for the year
# Cooling degree days represent the cumulative amount of cooling required to maintain a comfortable indoor temperature.
# In this example, we'll consider a base temperature of 20°C.
base_temperature = 20
cooling_degree_days = np.sum(np.maximum(temperature_data - base_temperature, 0))


print("Cooling Degree Days:", cooling_degree_days)

Mean Temperature: 27.138709677419353
Median Temperature: 26.7
Standard Deviation: 3.221668313492935
Number of Hot Days: 7
Cooling Degree Days: 221.3
