# Juan Hun PA 343.2.1

In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

### Tasks 1 and 2

In [13]:
a = np.array([1, 2, 3, 4, 5], dtype='int32')
print(a)
print(a.dtype)


[1 2 3 4 5]
int32


In [15]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype='float64')
print(b)
print(b.dtype)




[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


### Task 3

In [18]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

In [20]:
add = arr1 + arr2
sub = arr1 - arr2
div = arr1 / arr2
mul = arr1 * arr2

print(f"ADD: {add}")
print(f"SUB: {sub}")
print(f"DIV: {div}")
print(f"MUL: {mul}")

ADD: [ 5  7  9 11 13]
SUB: [-3 -3 -3 -3 -3]
DIV: [0.25       0.4        0.5        0.57142857 0.625     ]
MUL: [ 4 10 18 28 40]


In [21]:
dot_product = np.dot(arr1, arr2)

print(f"DOT: {dot_product}" )

DOT: 100


In [22]:
mean = np.mean(arr1)
median = np.median(arr1)
std_dev = np.std(arr1)

print(f"MEAN: {mean}")
print(f"MEDIAN: {median}")
print(f"STD_DEV: {std_dev}")

MEAN: 3.0
MEDIAN: 3.0
STD_DEV: 1.4142135623730951
